# https://taskfile.dev

version: '2'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: build
  dependencies:
    cmds:
      - yarn
  format:
    desc: ' '
    cmds:
      - |-
        npx prettier --write --list-different "**/*.{js,jsx,ts,tsx,css,less,scss,vue,json,gql,md,yml,yaml}"
  build:
    cmds:
      - yarn run tsc -p .
  build:watch:
    cmds:
      - yarn run tsc -p .
  prerequisites:
    deps: [prerequisites:node, prerequisites:yarn]
