# https://taskfile.dev

version: '2'

vars:
  PRETTIER_GLOB: '**/*.{js,jsx,ts,tsx,css,less,scss,vue,json,gql,md,yml,yaml}'

tasks:
  default:
    cmds:
      - task: dependencies
      - task: default:all
      - task: build
  default:all:
    deps: [format:check, lint, compile]
  dependencies:
    cmds:
      - yarn
  start:
    deps: [dependencies]
    cmds:
      - yarn run parcel src/index.html
  format:
    desc: ' '
    cmds:
      - npx prettier --write --list-different "{{.PRETTIER_GLOB}}"
  format:check:
    desc: ' '
    cmds:
      - npx prettier --list-different "{{.PRETTIER_GLOB}}"
  lint:
    desc: ' '
    cmds:
      - hadolint Dockerfile
  build:
    desc: ' '
    cmds:
      - yarn run parcel build src/index.html --out-dir out
  compile:
    cmds:
      - yarn run tsc -p .
  compile:watch:
    cmds:
      - yarn run tsc -p . --watch
  hook:format:
    desc: ' '
    cmds:
      - |-
        npx prettier --list-different "{{.PRETTIER_GLOB}}"
  prerequisites:
    deps:
      - prerequisites:node
      - prerequisites:yarn
      - prerequisites:lefthook
      - prerequisites:hadolint
  prerequisites:node:
    status:
      - command -v node
  prerequisites:yarn:
    status:
      - command -v yarn
  prerequisites:lefthook:
    status:
      - command -v lefthook
  prerequisites:hadolint:
    status:
      - command -v hadolint
